name: persona
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_test: ^7.1.0
  cloud_firestore: ^0.16.0
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  flutter_bloc: ^6.1.1
  intl_phone_field: ^1.4.2
  lottie: ^0.7.0+1
  pin_code_fields: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
